### ISSUE TITLE
Problems accessing the weights and data from BaiduYun

### ISSUE THREAD

**Issue by Nethrav22** [minhaolee/2D3DMATR#9]
Hi,

I'm having trouble downloading the weights and data from BaiduYun as it is not allowing me to make an account with a USA phone number. Could someone please provide me with an alternative way of downloading the weights or email me the zip file containing the weights? My email is nvenkat4@jh.edu. Any help would be greatly appreciated!!

Best,
Nethra

**Comment by murrdpirate** [comment]
I am also having issues downloading from BaiduYun. Are there any alternatives? I found the RGBDv2 dataset elsewhere, but the format is different and it's missing info like camera intrinsics.

**Comment by karim416** [comment]
I have the same problem. Have you found a way to get the data?
